### PR TITLE
Add Heroku support

### PR DESCRIPTION
**Pull request by nicolashery**
Tweaked a few things to make this easy to deploy to Heroku :)

Cheers,
Nicolas

### CODE REVIEW

**Comment by bundan** [comment]
This looks fine to me, while I imagine it's a corner case to think about have you been able to test this on Python on Windows? I haven't been able to do so myself yet. (I know, I know, it's just that there exist people that use it.)

**Comment by nicolashery** [comment]
Yeah you're right :)
I guess it works, Python being multiplatform and all, but I don't have a machine to test it :(

Setting the environment variables in a Windows environment will be the tricky point. Either:
- Let Windows developers figure out how to change the `.sh` into a batch file `.bat` using the `SET` command
- Update the readme explaining the above
- Include a `.bat` file
- Add a `config-sample.py` to be renamed to `config.py` that's imported in the main script if it exists and that allows to set those variables in Python (like the original version, except in a separate script)

And that's just testing locally. After that, deploying to Heroku from Windows or Unix should work fine both ways...

What do you think?

**Comment by bundan** [comment]
Hm, those are good ideas, but I feel that it might add more complexity than some people are willing to work with. (I'd do it myself given documentation, but I sense a few people will ask for help with `.bat` files.) 

I was thinking let's just leave the original script as-is and create a directory, like "heroku-deployment" on the repo with your improvements, because I feel like both methods has viable uses.

**Comment by nicolashery** [comment]
You're right, keeping it simple is important.

I'll think about that and push some new commits to this PR.

**Pull request closed without merging**
